[workspace]
resolver = "2"
members = [
    "crates/parking-domain",
    "crates/parking-events",
    "crates/parking-persistence",
    "services/parking-ingestion-worker",
    "services/parking-api",
    "tools/camera-simulator",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
async-nats = { version = "0.50", features = ["jetstream"] }
axum = "0.8"
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", default-features = false, features = ["chrono", "macros", "migrate", "postgres", "runtime-tokio", "uuid"] }
tokio = "1"
uuid = { version = "1", features = ["serde", "v4"] }
